import { RiskPrediction, AtRiskEmailAlert } from '../types';
import { AT_RISK_STUDENTS_LIST } from '../data/mockDatabase';

const STORAGE_KEY = 'smart_attendance_at_risk_email_alerts';

const INITIAL_SENT_ALERTS: AtRiskEmailAlert[] = [
  {
    id: 'alert-001',
    studentId: 'stu-001',
    studentName: 'Arun Kumar M.',
    rollNumber: '23CS104',
    email: 'arunkumar.m@institution.edu',
    attendancePercentage: 72.4,
    riskLevel: 'HIGH',
    triggerReason: 'Attendance fallen below mandatory 75% threshold (Current: 72.4%, -11.5% 30-day velocity drop)',
    recommendedAction: 'Attend all remaining 14 scheduled lecture sessions in DBMS and OS to achieve 76.2%.',
    sentAt: '2026-08-15 08:30 AM',
    status: 'delivered',
    subject: 'URGENT: Academic Attendance Alert & Recovery Plan (72.4%)',
    bodyPreview: 'Dear Arun Kumar M., your cumulative attendance in CSE Semester 5 has reached 72.4%, which is below the mandatory university cutoff of 75.0%...',
  },
  {
    id: 'alert-002',
    studentId: 'stu-018',
    studentName: 'Sneha R.',
    rollNumber: '23CS118',
    email: 'sneha.r@institution.edu',
    attendancePercentage: 74.1,
    riskLevel: 'MEDIUM',
    triggerReason: 'Marginal risk: Attendance at 74.1% with 3 consecutive Friday afternoon absences in Computer Networks',
    recommendedAction: 'Submit medical validation or attend next 4 lab practicals without absence.',
    sentAt: '2026-08-14 04:15 PM',
    status: 'opened',
    subject: 'Attendance Notice: Approaching Mandatory 75% Cutoff (74.1%)',
    bodyPreview: 'Dear Sneha R., this automated notification is to inform you that your current attendance standing is 74.1%...',
  },
];

class NotificationService {
  private alerts: AtRiskEmailAlert[] = [];

  constructor() {
    this.loadAlerts();
  }

  private loadAlerts() {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored) {
        this.alerts = JSON.parse(stored);
      } else {
        this.alerts = [...INITIAL_SENT_ALERTS];
        this.saveAlerts();
      }
    } catch {
      this.alerts = [...INITIAL_SENT_ALERTS];
    }
  }

  private saveAlerts() {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(this.alerts));
    } catch {
      // ignore
    }
  }

  public getAlertHistory(): AtRiskEmailAlert[] {
    return [...this.alerts];
  }

  /**
   * Evaluates a student against automated at-risk alert triggers:
   * 1. Overall attendance < 75%
   * 2. Risk Level === HIGH or MEDIUM
   * 3. 30-day trend decline > 8%
   * 4. Consecutive absences >= 2
   */
  public evaluateRiskTriggers(student: RiskPrediction): {
    isTriggered: boolean;
    triggerReason: string;
    priority: 'HIGH' | 'MEDIUM' | 'LOW';
  } {
    const reasons: string[] = [];

    if (student.overallAttendance < 75) {
      reasons.push(`Attendance at ${student.overallAttendance}% is below 75% university eligibility cutoff.`);
    }
    if (student.trendPercentageChange <= -8) {
      reasons.push(`Significant 30-day velocity drop (${student.trendPercentageChange}%).`);
    }
    if (student.consecutiveAbsences >= 2) {
      reasons.push(`${student.consecutiveAbsences} consecutive class absences recorded.`);
    }
    if (student.lowSubjectCount > 0) {
      reasons.push(`Lagging in ${student.lowSubjectCount} individual registered subject(s).`);
    }

    const isTriggered = reasons.length > 0 || student.riskLevel === 'HIGH';
    return {
      isTriggered,
      triggerReason: reasons.join(' ') || 'Automated predictive AI model flagged academic risk pattern.',
      priority: student.riskLevel,
    };
  }

  /**
   * Dispatch an automated email alert to an individual at-risk student
   */
  public async sendAtRiskEmailAlert(student: RiskPrediction): Promise<AtRiskEmailAlert> {
    const { triggerReason } = this.evaluateRiskTriggers(student);

    const emailSubject =
      student.riskLevel === 'HIGH'
        ? `[CRITICAL ACTION REQUIRED] Academic Attendance Warning - ${student.studentName} (${student.rollNumber})`
        : `[ATTENDANCE ADVISORY] Attendance Notice for ${student.studentName} (${student.rollNumber})`;

    const emailBody = `Dear ${student.studentName},

This is an official automated advisory from the Office of Academic Affairs regarding your attendance in ${student.departmentName}.

CURRENT STANDING:
• Cumulative Attendance: ${student.overallAttendance}%
• University Mandatory Minimum: 75.0%
• Deficit / Shortfall: ${(Math.max(0, 75 - student.overallAttendance)).toFixed(1)}%
• Risk Level: ${student.riskLevel}

TRIGGER ANALYSIS:
${triggerReason}

RECOMMENDED ACTION PLAN:
${student.recommendedAction || 'Attend all upcoming scheduled classes and consult your faculty academic advisor immediately.'}

CC: Department Head (${student.departmentName}), Academic Counselor

Note: This automated notification was generated by the Smart Attendance Anti-Proxy & Early Warning System.`;

    const newAlert: AtRiskEmailAlert = {
      id: `alert-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      studentId: student.studentId,
      studentName: student.studentName,
      rollNumber: student.rollNumber,
      email: `${student.studentName.toLowerCase().replace(/\s+/g, '.')}@institution.edu`,
      attendancePercentage: student.overallAttendance,
      riskLevel: student.riskLevel,
      triggerReason,
      recommendedAction: student.recommendedAction || 'Meet with faculty mentor and maintain 100% attendance in upcoming lectures.',
      sentAt: new Date().toLocaleString([], { dateStyle: 'short', timeStyle: 'short' }),
      status: 'sent',
      subject: emailSubject,
      bodyPreview: emailBody,
    };

    // Simulate network dispatch delay
    await new Promise((r) => setTimeout(r, 400));

    this.alerts.unshift(newAlert);
    this.saveAlerts();

    return newAlert;
  }

  /**
   * Automated batch run: scans all students and sends email alerts to all triggered students
   */
  public async runAutomatedBatchDispatch(studentsList: RiskPrediction[] = AT_RISK_STUDENTS_LIST): Promise<{
    dispatchedCount: number;
    dispatchedAlerts: AtRiskEmailAlert[];
  }> {
    const dispatchedAlerts: AtRiskEmailAlert[] = [];

    for (const student of studentsList) {
      const { isTriggered } = this.evaluateRiskTriggers(student);
      if (isTriggered) {
        const alert = await this.sendAtRiskEmailAlert(student);
        dispatchedAlerts.push(alert);
      }
    }

    return {
      dispatchedCount: dispatchedAlerts.length,
      dispatchedAlerts,
    };
  }

  /**
   * Batch dispatch email alerts to all provided at-risk students
   */
  public async sendBatchAtRiskEmailAlerts(studentsList: RiskPrediction[]): Promise<{
    count: number;
    alerts: AtRiskEmailAlert[];
  }> {
    const alerts: AtRiskEmailAlert[] = [];
    for (const student of studentsList) {
      const alert = await this.sendAtRiskEmailAlert(student);
      alerts.push(alert);
    }
    return {
      count: alerts.length,
      alerts,
    };
  }

  public clearHistory() {
    this.alerts = [];
    this.saveAlerts();
  }
}

export const notificationService = new NotificationService();
